/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * AutoGPT Agent Server
 * This server is used to execute agents that are created by the AutoGPT system.
 * OpenAPI spec version: 0.1
 */
import type { ProviderCostSummary } from "./providerCostSummary";
import type { UserCostSummary } from "./userCostSummary";
import type { CostBucket } from "./costBucket";

export interface PlatformCostDashboard {
  by_provider: ProviderCostSummary[];
  by_user: UserCostSummary[];
  total_cost_microdollars: number;
  total_requests: number;
  total_users: number;
  total_input_tokens: number;
  total_output_tokens: number;
  avg_input_tokens_per_request: number;
  avg_output_tokens_per_request: number;
  avg_cost_microdollars_per_request: number;
  cost_p50_microdollars: number;
  cost_p75_microdollars: number;
  cost_p95_microdollars: number;
  cost_p99_microdollars: number;
  cost_buckets: CostBucket[];
}
